name: Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout repo
        uses: actions/checkout@v5

      # Setup Bun using the official action
      - name: Setup Bun
        uses: oven-sh/setup-bun@v2

      # Install dependencies with Bun
      - name: Install dependencies
        run: |
          bun install || npm install

      # Update browserslist DB (optional but safe)
      - name: Update browserslist DB
        run: npx update-browserslist-db@latest
        continue-on-error: true

      # Build the project using Bun
      - name: Build project
        run: bun run build

      # Upload production-ready build files
      - name: Upload production-ready build files
        uses: actions/upload-pages-artifact@v4
        with:
          path: ./dist

  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      # Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
