name: Deploy

on:
  push:
    branches:
      - main

# (Optional) Set default permissions for the workflow
permissions:
  contents: read

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout repo
        uses: actions/checkout@v5

      # Setup Node.js with npm caching
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 23
          cache: 'npm'

      # Install dependencies
      - name: Install dependencies
        run: npm install

      # (Optional but recommended by GitHub Pages docs)
      - name: Configure Pages
        uses: actions/configure-pages@v5

      # Build the project with npm
      - name: Build project
        run: npm run build

      # Upload production-ready build files
      - name: Upload production-ready build files
        uses: actions/upload-pages-artifact@v4
        with:
          path: ./dist

  deploy:
    name: Deploy
    needs: build
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write

    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}

    steps:
      # Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
